language: python
python:
  - "3.6"
  - "3.7"
services:
  - elasticsearch
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.3.1-amd64.deb && sudo dpkg -i --force-confnew elasticsearch-7.3.1-amd64.deb && sudo service elasticsearch restart
install:
  - pip install tox-travis codecov
before_script:
  - sleep 30
script:
  - tox -e travis
after_success:
  - codecov --token="$CODECOV_TOKEN"