# Generated by Django 2.2.15 on 2020-11-10 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('scan_url', models.TextField(null=True)),
                ('tenant', models.CharField(max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('scan_url', models.TextField(null=True)),
                ('alert_id', models.CharField(max_length=256, null=True)),
                ('task_id', models.CharField(max_length=256, null=True)),
                ('document_id', models.CharField(max_length=256, null=True)),
                ('title', models.CharField(max_length=256, null=True)),
                ('group', models.CharField(max_length=256, null=True)),
                ('description', models.TextField()),
                ('source', models.CharField(max_length=256, null=True)),
                ('ip', models.CharField(max_length=256, null=True)),
                ('tenant', models.CharField(max_length=256, null=True)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='thehive.Case')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
