# Generated by Django 2.2.15 on 2020-11-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TheHive4LogConverter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('log_message', models.TextField()),
                ('tag', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TheHive4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('schema', models.CharField(choices=[('http', 'http'), ('https', 'https')], default='http', max_length=5)),
                ('host', models.CharField(max_length=128)),
                ('port', models.PositiveSmallIntegerField()),
                ('token', models.CharField(max_length=256)),
                ('insecure', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('vulnerability_status_converter', models.ManyToManyField(to='webhook.TheHive4LogConverter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
