# Generated by Django 2.2.9 on 2020-05-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elasticsearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='prefix',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug_name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
