# Generated by Django 2.2.13 on 2020-06-22 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elasticsearch', '0002_auto_20200503_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentregistry',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elasticsearch.Tenant'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='elasticsearch_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elasticsearch.Config'),
        ),
    ]
