# Generated by Django 2.2.9 on 2020-01-02 18:17

from django.db import migrations, models
import vmc.common.models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='access_complexity_v2',
            field=vmc.common.models.TupleValueField(blank=True, choices=[('H', 'HIGH'), ('M', 'MEDIUM'), ('L', 'LOW')], default='L', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cve',
            name='access_vector_v2',
            field=vmc.common.models.TupleValueField(blank=True, choices=[('L', 'LOCAL'), ('A', 'ADJACENT_NETWORK'), ('N', 'NETWORK')], default='L', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cve',
            name='attack_complexity_v3',
            field=vmc.common.models.TupleValueField(blank=True, choices=[('L', 'LOW'), ('H', 'HIGH')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cve',
            name='attack_vector_v3',
            field=vmc.common.models.TupleValueField(blank=True, choices=[('N', 'NETWORK'), ('A', 'ADJACENT_NETWORK'), ('L', 'LOCAL'), ('P', 'PHYSICAL')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cve',
            name='authentication_v2',
            field=vmc.common.models.TupleValueField(blank=True, choices=[('M', 'MULTIPLE'), ('S', 'SINGLE'), ('N', 'NONE')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cve',
            name='availability_impact_v2',
            field=vmc.common.models.TupleValueField(blank=True, choices=[('N', 'NONE'), ('P', 'PARTIAL'), ('C', 'COMPLETE')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cve',
            name='availability_impact_v3',
            field=vmc.common.models.TupleValueField(blank=True, choices=[('H', 'HIGH'), ('L', 'LOW'), ('N', 'NONE')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cve',
            name='confidentiality_impact_v2',
            field=vmc.common.models.TupleValueField(blank=True, choices=[('N', 'NONE'), ('P', 'PARTIAL'), ('C', 'COMPLETE')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cve',
            name='confidentiality_impact_v3',
            field=vmc.common.models.TupleValueField(blank=True, choices=[('H', 'HIGH'), ('L', 'LOW'), ('N', 'NONE')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cve',
            name='cpe',
            field=models.ManyToManyField(blank=True, to='knowledge_base.Cpe'),
        ),
        migrations.AlterField(
            model_name='cve',
            name='exploits',
            field=models.ManyToManyField(blank=True, to='knowledge_base.Exploit'),
        ),
        migrations.AlterField(
            model_name='cve',
            name='integrity_impact_v2',
            field=vmc.common.models.TupleValueField(blank=True, choices=[('N', 'NONE'), ('P', 'PARTIAL'), ('C', 'COMPLETE')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cve',
            name='integrity_impact_v3',
            field=vmc.common.models.TupleValueField(blank=True, choices=[('H', 'HIGH'), ('L', 'LOW'), ('N', 'NONE')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cve',
            name='privileges_required_v3',
            field=models.CharField(blank=True, choices=[('N', 'NONE'), ('L', 'LOW'), ('H', 'HIGH')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cve',
            name='scope_v3',
            field=models.CharField(blank=True, choices=[('N', 'NONE'), ('R', 'REQUIRED')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cve',
            name='user_interaction_v3',
            field=vmc.common.models.TupleValueField(blank=True, choices=[('N', 'NONE'), ('R', 'REQUIRED')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcve',
            name='access_complexity_v2',
            field=vmc.common.models.TupleValueField(blank=True, choices=[('H', 'HIGH'), ('M', 'MEDIUM'), ('L', 'LOW')], default='L', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcve',
            name='access_vector_v2',
            field=vmc.common.models.TupleValueField(blank=True, choices=[('L', 'LOCAL'), ('A', 'ADJACENT_NETWORK'), ('N', 'NETWORK')], default='L', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcve',
            name='attack_complexity_v3',
            field=vmc.common.models.TupleValueField(blank=True, choices=[('L', 'LOW'), ('H', 'HIGH')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcve',
            name='attack_vector_v3',
            field=vmc.common.models.TupleValueField(blank=True, choices=[('N', 'NETWORK'), ('A', 'ADJACENT_NETWORK'), ('L', 'LOCAL'), ('P', 'PHYSICAL')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcve',
            name='authentication_v2',
            field=vmc.common.models.TupleValueField(blank=True, choices=[('M', 'MULTIPLE'), ('S', 'SINGLE'), ('N', 'NONE')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcve',
            name='availability_impact_v2',
            field=vmc.common.models.TupleValueField(blank=True, choices=[('N', 'NONE'), ('P', 'PARTIAL'), ('C', 'COMPLETE')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcve',
            name='availability_impact_v3',
            field=vmc.common.models.TupleValueField(blank=True, choices=[('H', 'HIGH'), ('L', 'LOW'), ('N', 'NONE')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcve',
            name='confidentiality_impact_v2',
            field=vmc.common.models.TupleValueField(blank=True, choices=[('N', 'NONE'), ('P', 'PARTIAL'), ('C', 'COMPLETE')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcve',
            name='confidentiality_impact_v3',
            field=vmc.common.models.TupleValueField(blank=True, choices=[('H', 'HIGH'), ('L', 'LOW'), ('N', 'NONE')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcve',
            name='integrity_impact_v2',
            field=vmc.common.models.TupleValueField(blank=True, choices=[('N', 'NONE'), ('P', 'PARTIAL'), ('C', 'COMPLETE')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcve',
            name='integrity_impact_v3',
            field=vmc.common.models.TupleValueField(blank=True, choices=[('H', 'HIGH'), ('L', 'LOW'), ('N', 'NONE')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcve',
            name='privileges_required_v3',
            field=models.CharField(blank=True, choices=[('N', 'NONE'), ('L', 'LOW'), ('H', 'HIGH')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcve',
            name='scope_v3',
            field=models.CharField(blank=True, choices=[('N', 'NONE'), ('R', 'REQUIRED')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcve',
            name='user_interaction_v3',
            field=vmc.common.models.TupleValueField(blank=True, choices=[('N', 'NONE'), ('R', 'REQUIRED')], max_length=1, null=True),
        ),
    ]
