# Generated by Django 2.2.13 on 2020-06-22 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0002_auto_20200614_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elasticsearch.Tenant'),
        ),
    ]
