# Generated by Django 2.2.13 on 2020-06-30 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0003_auto_20200622_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elasticsearch.Tenant'),
        ),
    ]
