# Generated by Django 2.2.13 on 2020-07-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0004_auto_20200630_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='filter',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
