# Generated by Django 2.2.13 on 2020-09-02 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0005_config_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('file', models.TextField()),
                ('file_id', models.CharField(max_length=64)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scanners.Config')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
