# Generated by Django 2.2.15 on 2020-11-05 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0006_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanners.Config'),
        ),
    ]
