# Generated by Django 2.2.9 on 2020-04-08 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elasticsearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('host', models.CharField(max_length=128)),
                ('port', models.PositiveSmallIntegerField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('last_scans_pull', models.DateTimeField(default=None)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenant_ov', to='elasticsearch.Tenant')),
            ],
            options={
                'db_table': 'open_vas_config',
            },
        ),
    ]
