# Generated by Django 2.2.9 on 2020-01-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('schema', models.CharField(choices=[('http', 'http'), ('https', 'https')], default='http', max_length=5)),
                ('host', models.CharField(max_length=128)),
                ('port', models.PositiveSmallIntegerField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('insecure', models.BooleanField(default=False))
            ],
            options={
                'abstract': False,
            },
        ),
    ]
