# Generated by Django 2.2.9 on 2020-05-23 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ralph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tenant', to='elasticsearch.Tenant'),
        ),
    ]
