# Generated by Django 2.2.4 on 2019-11-30 15:23

import vmc.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('ip_address', models.CharField(max_length=16)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('os', models.CharField(blank=True, max_length=128)),
                ('responsible_person', models.EmailField(blank=True, max_length=254, null=True)),
                ('confidentiality_requirement', vmc.common.models.TupleValueField(choices=[('L', 'LOW'), ('M', 'MEDIUM'), ('H', 'HIGH'), ('N', 'NOT_DEFINED')], default='N', max_length=1)),
                ('integrity_requirement', vmc.common.models.TupleValueField(choices=[('L', 'LOW'), ('M', 'MEDIUM'), ('H', 'HIGH'), ('N', 'NOT_DEFINED')], default='N', max_length=1)),
                ('availability_requirement', vmc.common.models.TupleValueField(choices=[('L', 'LOW'), ('M', 'MEDIUM'), ('H', 'HIGH'), ('N', 'NOT_DEFINED')], default='N', max_length=1)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, vmc.common.models.ModelDiffMixin),
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('svc_name', models.CharField(max_length=32)),
                ('protocol', models.CharField(max_length=3)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, vmc.common.models.ModelDiffMixin),
        ),
    ]
