# Generated by Django 2.2.9 on 2019-12-26 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalasset',
            name='responsible_person',
        ),
    ]
